apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-file-integrity

resources:
- ../../../../components/file-integrity-operator/base

patches:
- path: subscription-channel.yaml
  target:
    kind: Subscription
