apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: external-secrets-operator
spec:
  name: external-secrets-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  channel: patchme
  installPlanApproval: patchme
