apiVersion: v1
kind: Namespace
metadata:
  name: overridden_by_kustomize
  labels:
    openshift.io/cluster-monitoring: "true"
    pod-security.kubernetes.io/enforce: privileged
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
